framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        default_bus: auth.bus
        buses:
            auth.bus:
                middleware:
                    - SimplePayment\Core\Infrastructure\Middleware\AuthenticationMiddleware
                    - validation
                    - doctrine_transaction
            authless.bus:
                middleware:
                    - validation
                    - doctrine_transaction

        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'
            async: 
                dsn: "doctrine://default?queue_name=async"
                options:
                    auto_setup: false

            failed: 
                dsn: "doctrine://default?queue_name=failed"
                options:
                    auto_setup: false

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            SimplePayment\Core\Application\Async\SendPaymentNotification: async